### ISSUE TITLE
飞书用户同步报错

### ISSUE THREAD

**Issue by clhlc** [topiam/eiam#53]
```shell
2024-12-16 17:26:51.309 [DEBUG] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.SQL                        Line:135 :  insert into eiam_identity_source_sync_history (batch_,create_by,create_time,created_count,deleted_count,end_time,identity_source_id,object_type,remark_,skipped_count,start_time,status_,trigger_type,update_by,update_time,updated_count,is_deleted,id_) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,false,?)
2024-12-16 17:26:51.310 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (1:VARCHAR) <- [hiUr3ko]
2024-12-16 17:26:51.310 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (2:VARCHAR) <- [anonymousUser]
2024-12-16 17:26:51.310 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (3:TIMESTAMP) <- [2024-12-16T17:26:51.307486334]
2024-12-16 17:26:51.311 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:35  :  binding parameter (4:INTEGER) <- [null]
2024-12-16 17:26:51.311 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:35  :  binding parameter (5:INTEGER) <- [null]
2024-12-16 17:26:51.311 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:35  :  binding parameter (6:TIMESTAMP) <- [null]
2024-12-16 17:26:51.311 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (7:VARCHAR) <- [ac120004-93ce-15d8-8193-cec900280009]
2024-12-16 17:26:51.312 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (8:VARCHAR) <- [user]
2024-12-16 17:26:51.313 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:35  :  binding parameter (9:VARCHAR) <- [null]
2024-12-16 17:26:51.313 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:35  :  binding parameter (10:INTEGER) <- [null]
2024-12-16 17:26:51.313 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (11:TIMESTAMP) <- [2024-12-16T17:26:38.567144185]
2024-12-16 17:26:51.313 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (12:VARCHAR) <- [pending]
2024-12-16 17:26:51.313 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (13:VARCHAR) <- [manual]
2024-12-16 17:26:51.314 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (14:VARCHAR) <- [anonymousUser]
2024-12-16 17:26:51.314 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (15:TIMESTAMP) <- [2024-12-16T17:26:51.307486334]
2024-12-16 17:26:51.314 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:35  :  binding parameter (16:INTEGER) <- [null]
2024-12-16 17:26:51.316 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (17:VARCHAR) <- [ac120004-93ce-15d8-8193-cecab4ab000d]
2024-12-16 17:26:51.333 [DEBUG] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.SQL                        Line:135 :  select oe1_0.id_,oe1_0.code_,oe1_0.create_by,oe1_0.create_time,oe1_0.data_origin,oe1_0.display_path,oe1_0.is_enabled,oe1_0.external_id,oe1_0.identity_source_id,oe1_0.is_leaf,oe1_0.name_,oe1_0.order_,oe1_0.parent_id,oe1_0.path_,oe1_0.remark_,oe1_0.update_by,oe1_0.update_time from eiam_organization oe1_0 where oe1_0.identity_source_id=? and oe1_0.is_deleted=false
2024-12-16 17:26:51.334 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (1:VARCHAR) <- [ac120004-93ce-15d8-8193-cec900280009]
2024-12-16 17:26:51.354 [DEBUG] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.SQL                        Line:135 :  select ue1_0.id_,ue1_0.auth_total,ue1_0.avatar_,ue1_0.create_by,ue1_0.create_time,ue1_0.data_origin,ue1_0.email_,ue1_0.email_verified,ue1_0.expand_,ue1_0.expire_date,ue1_0.external_id,ue1_0.full_name,ue1_0.identity_source_id,ue1_0.last_auth_ip,ue1_0.last_auth_time,ue1_0.last_update_password_time,ue1_0.lock_expired_time,ue1_0.need_change_password,ue1_0.nick_name,ue1_0.password_,ue1_0.phone_,ue1_0.phone_area_code,ue1_0.phone_verified,ue1_0.remark_,ue1_0.status_,ue1_0.update_by,ue1_0.update_time,ue1_0.user_type,ue1_0.username_ from eiam_user ue1_0 where ue1_0.identity_source_id=? and ue1_0.is_deleted=false
2024-12-16 17:26:51.355 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (1:VARCHAR) <- [ac120004-93ce-15d8-8193-cec900280009]
2024-12-16 17:26:51.358 [ERROR] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  r.DefaultIdentitySourceUserPostProcessor Line:151 :  处理用户数据发生异常

java.lang.IllegalStateException: Duplicate key 324cc97e-146c-4128-91f6-83066577e582 (attempted merging values OrganizationEntity(name=飞书, code=sWiJQDy, parentId=root, path=/root/324cc97e-146c-4128-91f6-83066577e582, displayPath=/TOPIAM Employee/飞书, externalId=0, dataOrigin=feishu, identitySourceId=ac120004-93ce-15d8-8193-cec900280009, order=9999, leaf=false, enabled=true) and OrganizationEntity(name=飞书, code=sWiJQDy, parentId=root, path=/root/324cc97e-146c-4128-91f6-83066577e582, displayPath=/TOPIAM Employee/飞书, externalId=0, dataOrigin=feishu, identitySourceId=ac120004-93ce-15d8-8193-cec900280009, order=9999, leaf=false, enabled=true))
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at cn.topiam.employee.synchronizer.processor.DefaultIdentitySourceUserPostProcessor.initData(DefaultIdentitySourceUserPostProcessor.java:367)
	at cn.topiam.employee.synchronizer.processor.DefaultIdentitySourceUserPostProcessor.process(DefaultIdentitySourceUserPostProcessor.java:97)
	at cn.topiam.employee.identitysource.core.AbstractDefaultIdentitySource.sync(AbstractDefaultIdentitySource.java:88)
	at cn.topiam.employee.synchronizer.configuration.IdentitySourceBeanRegistry.sync(IdentitySourceBeanRegistry.java:314)
	at cn.topiam.employee.identitysource.core.event.IdentitySourceEventListenerRunner.lambda$run$0(IdentitySourceEventListenerRunner.java:70)
	at org.redisson.PubSubMessageListener.onMessage(PubSubMessageListener.java:79)
	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:68)
	at org.redisson.client.handler.CommandPubSubDecoder.lambda$enqueueMessage$2(CommandPubSubDecoder.java:221)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

2024-12-16 17:26:51.369 [DEBUG] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.SQL                        Line:135 :  select isshe1_0.id_,isshe1_0.batch_,isshe1_0.create_by,isshe1_0.create_time,isshe1_0.created_count,isshe1_0.deleted_count,isshe1_0.end_time,isshe1_0.identity_source_id,isshe1_0.object_type,isshe1_0.remark_,isshe1_0.skipped_count,isshe1_0.start_time,isshe1_0.status_,isshe1_0.trigger_type,isshe1_0.update_by,isshe1_0.update_time,isshe1_0.updated_count from eiam_identity_source_sync_history isshe1_0 where isshe1_0.is_deleted=false and isshe1_0.id_=?
2024-12-16 17:26:51.369 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (1:VARCHAR) <- [ac120004-93ce-15d8-8193-cecab4ab000d]
2024-12-16 17:26:51.373 [DEBUG] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.SQL                        Line:135 :  update eiam_identity_source_sync_history set batch_=?,create_by=?,create_time=?,created_count=?,deleted_count=?,end_time=?,identity_source_id=?,object_type=?,remark_=?,skipped_count=?,start_time=?,status_=?,trigger_type=?,update_by=?,update_time=?,updated_count=? where id_=?
2024-12-16 17:26:51.373 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (1:VARCHAR) <- [hiUr3ko]
2024-12-16 17:26:51.374 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (2:VARCHAR) <- [anonymousUser]
2024-12-16 17:26:51.374 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (3:TIMESTAMP) <- [2024-12-16T17:26:51.307486334]
2024-12-16 17:26:51.374 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:35  :  binding parameter (4:INTEGER) <- [null]
2024-12-16 17:26:51.375 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:35  :  binding parameter (5:INTEGER) <- [null]
2024-12-16 17:26:51.375 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (6:TIMESTAMP) <- [2024-12-16T17:26:51.368012502]
2024-12-16 17:26:51.375 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (7:VARCHAR) <- [ac120004-93ce-15d8-8193-cec900280009]
2024-12-16 17:26:51.375 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (8:VARCHAR) <- [user]
2024-12-16 17:26:51.376 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:35  :  binding parameter (9:VARCHAR) <- [null]
2024-12-16 17:26:51.376 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:35  :  binding parameter (10:INTEGER) <- [null]
2024-12-16 17:26:51.376 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (11:TIMESTAMP) <- [2024-12-16T17:26:38.567144185]
2024-12-16 17:26:51.377 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (12:VARCHAR) <- [fail]
2024-12-16 17:26:51.377 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (13:VARCHAR) <- [manual]
2024-12-16 17:26:51.378 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (14:VARCHAR) <- [anonymousUser]
2024-12-16 17:26:51.378 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (15:TIMESTAMP) <- [2024-12-16T17:26:51.372473718]
2024-12-16 17:26:51.378 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:35  :  binding parameter (16:INTEGER) <- [null]
2024-12-16 17:26:51.379 [TRACE] [] [] [9233716f-8f50-44b8-b8a8-f303e506072b] 1 --  org.hibernate.orm.jdbc.bind              Line:24  :  binding parameter (17:VARCHAR) <- [ac120004-93ce-15d8-8193-cecab4ab000d]
2024-12-16 17:26:51.390 [INFO ] [] [] [] 1 --  configuration.IdentitySourceBeanRegistry Line:324 :  [手动任务]-同步身份源[飞书]数据结束, 执行时长: 24602 ms
```

<img width="1648" alt="image" src="https://github.com/user-attachments/assets/02c522c3-fcbc-4604-9b9d-eede0108bf5c" />

**Comment by clhlc** [comment]
bug已经修复

**Comment by clhlc** [comment]
bug已经修复
